site_name: Kavaler
plugins:
  - macros
theme:
  name: material
  logo: img/kavaler_100px.png
  favicon: img/kavaler_32px.png
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Elements: elements.md
  - Element Details: element_details.md
  - Type Tree: typetree.md
  - Type Chains: typechain.md
  - Constraints: constraints.md
  - Constraints by name: constraints_by_name.md
  - Other/general constraints: general_constraints.md
